"""
Django settings for industry_analyser project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import textwrap
from urllib.parse import quote_plus

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    BASE_URL=(str, 'http://127.0.0.1:8000'),
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'), overwrite=False)

# CA PEM from env (DB_SSL_CERT or legacy capem), written to /tmp — same pattern as Vercel/GCP.
_DB_SSL_CA_FILE = '/tmp/industry-analyser-postgres-ca.pem'


def _normalize_db_ssl_pem_raw(raw: str) -> str:
    if not raw:
        return ''
    s = raw.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        s = s[1:-1]
    if '\\n' in s and s.count('\n') < 4:
        s = s.replace('\\n', '\n')
    return s.strip()


def _db_ssl_pem_from_env() -> str:
    return _normalize_db_ssl_pem_raw(
        os.environ.get('DB_SSL_CERT') or os.environ.get('capem') or ''
    )


def _format_db_ssl_pem(capem_content):
    stripped = capem_content.strip()
    if '\n' in stripped:
        return stripped if stripped.endswith('\n') else stripped + '\n'
    lines = capem_content.replace(
        '-----BEGIN CERTIFICATE----- ',
        '-----BEGIN CERTIFICATE-----\n',
    )
    lines = lines.replace(
        ' -----END CERTIFICATE-----',
        '\n-----END CERTIFICATE-----',
    )
    parts = lines.split('\n')
    if len(parts) >= 3:
        base64_content = ''.join(parts[1:-1]).replace(' ', '')
        formatted_content = textwrap.fill(base64_content, 64)
        return (
            f'-----BEGIN CERTIFICATE-----\n'
            f'{formatted_content}\n'
            f'-----END CERTIFICATE-----'
        )
    return capem_content


def _apply_db_ssl_cert(db_config, db_ssl_cert_content, ca_pem_path):
    if not db_ssl_cert_content:
        return
    pem_content = _format_db_ssl_pem(db_ssl_cert_content)
    with open(ca_pem_path, 'w') as f:
        f.write(pem_content)
    db_config.setdefault('OPTIONS', {})
    db_config['OPTIONS']['sslmode'] = 'require'
    db_config['OPTIONS']['sslrootcert'] = ca_pem_path


SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
BASE_URL = env('BASE_URL')
HARD_CODED_PASSWORD = env('HARD_CODED_PASSWORD', default='')
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')

ALLOWED_HOSTS = [
    '127.0.0.1',
    '0.0.0.0',
    'industry-analyser-180632294935.europe-north1.run.app'
]

_extra_host = env('ALLOWED_HOST_IP', default='')
if _extra_host:
    ALLOWED_HOSTS.append(_extra_host)

# CSRF trusted origins for Cloud Run
CSRF_TRUSTED_ORIGINS = [
    'https://industry-analyser-180632294935.europe-north1.run.app',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fetcher',
    'accounts',
    'tv_programs',
    'blogs',
    'classified_ads',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'industry_analyser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'industry_analyser.wsgi.app'


def _database_url_default() -> str:
    """Prefer DATABASE_URL; otherwise build from legacy DB_* vars (still set on Vercel)."""
    explicit = os.environ.get('DATABASE_URL', '').strip()
    if explicit:
        return explicit
    host = os.environ.get('DB_HOST', '').strip()
    if not host:
        return 'sqlite:///db.sqlite3'
    user = os.environ.get('DB_USER', '')
    password = os.environ.get('DB_PASSWORD', '')
    name = os.environ.get('DB_NAME', '')
    port = os.environ.get('DB_PORT', '5432')
    return (
        f'postgres://{quote_plus(user)}:{quote_plus(password)}'
        f'@{host}:{port}/{name}?sslmode=require'
    )


DATABASES = {
    'default': env.db('DATABASE_URL', default=_database_url_default())
}

db_ssl_cert = _db_ssl_pem_from_env()
if db_ssl_cert:
    _apply_db_ssl_cert(DATABASES['default'], db_ssl_cert, _DB_SSL_CA_FILE)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def create_log_handler(
    handler_name, level, filename=None, max_bytes=10485760, backup_count=10
):
    """Creates a log handler, either for a file or null if in debug mode."""
    if DEBUG and filename:
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)
        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '{levelname} {asctime} {module} {process:d} '
                '{thread:d} {message}'
            ),
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'tv_programs': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'core_scraper': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'fetcher': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'blogs': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'classified_ads': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
