"""
Django settings for industry_analyser project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import json
import os
import textwrap

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Settings Configuration ---
# Use individual environment variables on Vercel, local file otherwise

IS_VERCEL = os.environ.get('VERCEL') == '1'

if IS_VERCEL:
    print("I'm on Vercel!")
    # On Vercel: Use individual environment variables
    def get_env(key, default=None, required=False):
        value = os.environ.get(key, default)
        if required and value is None:
            raise ValueError(f"Required environment variable '{key}' is not set")
        return value
    
    # Create ca.pem at runtime if database cert is provided
    CA_PEM_PATH = None
    capem_content = os.environ.get('DB_SSL_CERT')
    if capem_content:
        CA_PEM_PATH = '/tmp/ca.pem'
        if not os.path.exists(CA_PEM_PATH):
            # Reformat the single-line env var into valid PEM format
            lines = capem_content.replace(
                "-----BEGIN CERTIFICATE----- ",
                "-----BEGIN CERTIFICATE-----\n"
            )
            lines = lines.replace(
                " -----END CERTIFICATE-----",
                "\n-----END CERTIFICATE-----"
            )
            base64_content = lines.split("\n", 1)[1].rsplit("\n", 1)[0]
            formatted_content = textwrap.fill(base64_content, 64)
            pem_content = (
                f"-----BEGIN CERTIFICATE-----\n"
                f"{formatted_content}\n"
                f"-----END CERTIFICATE-----"
            )
            with open(CA_PEM_PATH, 'w') as f:
                f.write(pem_content)
else:
    # Local development: Use private_settings.json
    PRIVATE_SETTINGS_JSON_PATH = os.path.join(
        BASE_DIR, 'private_settings.json'
    )
    
    if not os.path.isfile(PRIVATE_SETTINGS_JSON_PATH):
        raise FileNotFoundError(
            'Private settings do not exist. '
            'Please provide private_settings.json'
        )
    
    with open(PRIVATE_SETTINGS_JSON_PATH, 'r') as file:
        private_settings = json.load(file)
    
    def get_env(key, default=None, required=False):
        return private_settings.get(key, default)
    
    CA_PEM_PATH = os.path.join(BASE_DIR, 'ca.pem')

# --- End Settings Configuration ---


# Quick-start development settings - unsuitable for production
SECRET_KEY = get_env('SECRET_KEY', required=True)
DEBUG = get_env('DEBUG', 'False') == 'True'
BASE_URL = get_env('BASE_URL')
HARD_CODED_PASSWORD = get_env('HARD_CODED_PASSWORD')
GEMINI_API_KEY = get_env('GEMINI_API_KEY')

ON_VERCEL = os.environ.get('VERCEL', False)

ALLOWED_HOSTS = [
    '127.0.0.1',
    '0.0.0.0',
    '.vercel.app'
]

if not IS_VERCEL:
    ip_address = get_env('ip_address')
    if ip_address:
        ALLOWED_HOSTS.append(ip_address)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fetcher',
    'accounts',
    'tv_programs',
    'blogs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'industry_analyser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'industry_analyser.wsgi.app'

# Database
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    if IS_VERCEL:
        # On Vercel: Build database config from individual env vars
        db_config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_env('DB_NAME', required=True),
            'USER': get_env('DB_USER', required=True),
            'PASSWORD': get_env('DB_PASSWORD', required=True),
            'HOST': get_env('DB_HOST', required=True),
            'PORT': get_env('DB_PORT', '5432'),
        }
        
        # Add SSL options if certificate is provided
        if CA_PEM_PATH:
            db_config['OPTIONS'] = {
                'sslmode': 'require',
                'sslrootcert': CA_PEM_PATH
            }
        
        DATABASES = {'default': db_config}
    else:
        # Local: Use DATABASES from private_settings.json
        DATABASES = get_env('DATABASES')


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def create_log_handler(
    handler_name, level, filename=None, max_bytes=10485760, backup_count=10
):
    """Creates a log handler, either for a file or null if in debug mode."""
    if DEBUG and filename:
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)
        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '{levelname} {asctime} {module} {process:d} {thread:d} {message}'
            ),
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'tv_programs': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'core_scraper': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'fetcher': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'blogs': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
