"""
Django settings for industry_analyser project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import json
import os
import textwrap

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Runtime File Generation for Vercel ---

IS_VERCEL = os.environ.get('VERCEL') == '1'

# 1. Handle private_settings.json
if IS_VERCEL:
    # Use the /tmp directory for writable storage in Vercel
    PRIVATE_SETTINGS_JSON_PATH = '/tmp/private_settings.json'
else:
    PRIVATE_SETTINGS_JSON_PATH = os.path.join(
        BASE_DIR, 'private_settings.json'
    )

# Create the file from environment variables if it doesn't exist
if not os.path.exists(PRIVATE_SETTINGS_JSON_PATH):
    private_settings_str = os.environ.get('private_settings')
    if private_settings_str:
        with open(PRIVATE_SETTINGS_JSON_PATH, 'w') as f:
            f.write(private_settings_str)
    else:
        raise FileNotFoundError(
            "'private_settings.json' not found and 'private_settings' "
            "env var is not set."
        )

# Now, load the settings from the file
try:
    with open(PRIVATE_SETTINGS_JSON_PATH, 'r') as f:
        private_settings = json.load(f)
except (FileNotFoundError, json.JSONDecodeError) as e:
    raise RuntimeError(
        f"Could not load private settings from {PRIVATE_SETTINGS_JSON_PATH}: {e}"
    )

# 2. Handle ca.pem for the database
if IS_VERCEL:
    CA_PEM_PATH = '/tmp/ca.pem'
    # Create ca.pem at runtime if it doesn't exist
    if not os.path.exists(CA_PEM_PATH):
        capem_content = os.environ.get('capem')
        if capem_content:
            # Reformat the single-line env var into a valid PEM format
            lines = capem_content.replace("-----BEGIN CERTIFICATE----- ", "-----BEGIN CERTIFICATE-----\\n")
            lines = lines.replace(" -----END CERTIFICATE-----", "\\n-----END CERTIFICATE-----")
            base64_content = lines.split("\\n", 1)[1].rsplit("\\n", 1)[0]
            formatted_content = textwrap.fill(base64_content, 64)
            pem_content = f"-----BEGIN CERTIFICATE-----\\n{formatted_content}\\n-----END CERTIFICATE-----"
            with open(CA_PEM_PATH, 'w') as f:
                f.write(pem_content)
else:
    CA_PEM_PATH = os.path.join(BASE_DIR, 'ca.pem')

# --- End Runtime File Generation ---


# Quick-start development settings - unsuitable for production
SECRET_KEY = private_settings.get('SECRET_KEY')
DEBUG = private_settings.get('DEBUG')
BASE_URL = private_settings.get('base_url')
HARD_CODED_PASSWORD = private_settings.get('HARD_CODED_PASSWORD')
GEMINI_API_KEY = private_settings.get('gemini_api_key')

ON_VERCEL = os.environ.get('VERCEL', False)

ALLOWED_HOSTS = [
  '127.0.0.1',
  '0.0.0.0',
  private_settings.get('ip_address'),
  '.vercel.app'
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fetcher',
    'accounts',
    'tv_programs',
    'blogs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'industry_analyser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'industry_analyser.wsgi.app'

# Database
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = private_settings.get('DATABASES')
    # IMPORTANT: Update the database config to use the runtime ca.pem path on Vercel
    if IS_VERCEL and DATABASES:
        db_options = DATABASES.get('default', {}).get('OPTIONS', {})
        if db_options and 'sslrootcert' in db_options:
            db_options['sslrootcert'] = CA_PEM_PATH


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def create_log_handler(
    handler_name, level, filename=None, max_bytes=10485760, backup_count=10
):
    """Creates a log handler, either for a file or null if in debug mode."""
    if DEBUG and filename:
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)
        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '{levelname} {asctime} {module} {process:d} {thread:d} {message}'
            ),
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'tv_programs': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'core_scraper': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'fetcher': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'blogs': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
