# Generated by Django 5.0.4 on 2025-09-30 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('should_scrape', models.BooleanField(default=True, help_text='Whether this channel should be included in scraping')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_lv', models.CharField(max_length=500)),
                ('title_eng', models.CharField(max_length=500)),
                ('description_lv', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('title_match_ratio', models.FloatField(default=0)),
                ('description_match_ratio', models.FloatField(default=0)),
                ('combined_match_ratio', models.FloatField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tv_programs.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_programs.category')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_programs.program')),
            ],
            options={
                'db_table': 'tv_programs_program_categories',
                'unique_together': {('program', 'category')},
            },
        ),
        migrations.AddField(
            model_name='program',
            name='categories',
            field=models.ManyToManyField(through='tv_programs.ProgramCategory', to='tv_programs.category'),
        ),
    ]
