# Generated by Django 4.2.23 on 2025-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_programs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['pg_rating', 'start_time'], name='tv_programs_pg_rati_b43d90_idx'),
        ),
    ]
