# Generated by Django 5.2.8 on 2026-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_programs', '0002_program_tv_programs_pg_rati_b43d90_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
