# Generated by Django 4.2.6 on 2026-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_programs', '0003_alter_program_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='classification_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='program',
            name='classification_reasoning',
            field=models.CharField(blank=True, help_text='Which rule fired, e.g. title contains a seriāls keyword.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('not_movie', 'Not a movie'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='enrichment_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
