# Generated by Django 5.2.8 on 2026-10-02 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_programs', '0004_content_classification_and_enrichment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='source_event_id',
            field=models.CharField(blank=True, help_text='tet.lv per-airing event id (show-expander data-id)', max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_lv', models.CharField(max_length=500)),
                ('series_title', models.CharField(blank=True, max_length=500)),
                ('series_season', models.IntegerField(blank=True, null=True)),
                ('series_episode', models.IntegerField(blank=True, null=True)),
                ('description_lv', models.TextField(blank=True, null=True)),
                ('dedup_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title_eng', models.CharField(blank=True, max_length=500, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('imdb_url', models.URLField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pg_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('not_movie', 'Not a movie'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('classification_confidence', models.FloatField(default=0.0)),
                ('classification_reasoning', models.CharField(blank=True, max_length=255, null=True)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('not_found', 'Not found'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('enrichment_source', models.CharField(blank=True, max_length=20, null=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('title_match_ratio', models.FloatField(default=0)),
                ('is_excluded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='tv_programs.category')),
            ],
            options={
                'db_table': 'tv_programs_show',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airings', to='tv_programs.show'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('show', 'channel', 'start_time')},
        ),
        migrations.CreateModel(
            name='ShowPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tv_programs.show')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tv_programs_show_preference',
                'unique_together': {('show', 'user')},
            },
        ),
    ]
