# Generated by Django 5.2.8 on 2025-11-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_page_pageanalysis_theme_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanalysis',
            name='theme_match',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
