# Generated by Django 5.2.8 on 2025-11-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_pageanalysis_theme_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanalysis',
            name='model',
            field=models.CharField(default='gemini-2.5-flash-lite', max_length=100),
            preserve_default=False,
        ),
    ]
