# Generated by Django 5.2.8 on 2025-12-04 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_pageanalysis_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalysisReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_approved', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.pageanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
