# Generated by Django 5.2.8 on 2025-12-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_pageanalysisreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['analysis_order', 'name']},
        ),
        migrations.AddField(
            model_name='theme',
            name='analysis_order',
            field=models.IntegerField(default=0, help_text='Order in which this theme is analyzed (lower = first)'),
        ),
    ]
