# Generated by Django 5.2.8 on 2025-12-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_theme_options_theme_analysis_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='has_video',
            field=models.BooleanField(default=False, help_text='Page contains video content or mentions video'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_count',
            field=models.IntegerField(default=0, help_text='Number of images in the page'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_length',
            field=models.IntegerField(default=0, help_text='Length of text content in characters'),
        ),
        migrations.AddField(
            model_name='page',
            name='video_count',
            field=models.IntegerField(default=0, help_text='Number of video embeds detected'),
        ),
    ]
