# Generated by Django 5.2.8 on 2025-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_page_has_video_page_image_count_page_text_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanalysis',
            name='model_tier',
            field=models.CharField(choices=[('cheap', 'Cheap/Rough Model'), ('expensive', 'Expensive/Precise Model')], default='expensive', help_text='Tier of model used for analysis', max_length=20),
        ),
    ]
