# Generated by Django 5.2.8 on 2026-09-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0001_initial'),
        ('blogs', '0009_pageanalysis_model_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanalysis',
            name='ai_model',
            field=models.ForeignKey(blank=True, help_text='Served AI model that produced this analysis (null for content_analyzer and legacy rows)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_analyses', to='ai_providers.aimodel'),
        ),
        migrations.AddField(
            model_name='pageanalysis',
            name='ai_request',
            field=models.ForeignKey(blank=True, help_text='AIRequest row that produced this analysis', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_analyses', to='ai_providers.airequest'),
        ),
    ]
