/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/vacancies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Vacancies
         * @description Vacancy list page payload — mirrors the retired
         *     find_vacancies view's filtering exactly.
         */
        get: operations["fetcher_api_list_vacancies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Company list — mirrors company_list: canonical companies
         *     only (merged-away rows hidden), name/reg-code search.
         */
        get: operations["fetcher_api_list_companies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/companies/{pk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Company Detail
         * @description Company detail — mirrors the company_detail view. A merged
         *     company resolves to its canonical survivor (the old view 301'd
         *     there; the API returns the canonical record directly).
         */
        get: operations["fetcher_api_company_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/keywords/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Keyword
         * @description Create a keyword — session-auth replacement for the retired
         *     HARD_CODED_PASSWORD form. Validation still goes through
         *     KeywordForm so name normalization/uniqueness are unchanged.
         */
        post: operations["fetcher_api_add_keyword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tv/programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Programs
         * @description Program feed — mirrors the retired program_list view.
         *
         *     `not_content_rating` defaults to 'R' when the param is absent;
         *     an explicit empty value (?not_content_rating=) disables the
         *     exclusion, like clearing the template input did. `ratio` was a
         *     declared-but-dead input in the template form — it now filters on
         *     the displayed match ratio (show's when truthy, falling back to
         *     the program's like the card's |default-style fallback).
         */
        get: operations["tv_programs_api_list_programs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tv/spoki-page/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spoki Page
         * @description Live-fetches the hardcoded spoki.lv article and returns
         *     {title, content} — the SPA renders content as HTML (same trust
         *     posture as the template's |safe render).
         */
        get: operations["tv_programs_api_spoki_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tv/shows/{show_id}/react/{reaction}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * React To Show
         * @description Toggle a like/dislike on a Show — posting the same reaction
         *     again removes it. Session-auth (was: anonymous form POST).
         */
        post: operations["tv_programs_api_react_to_show"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tv/programs/{program_id}/react/{reaction}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * React To Program
         * @description Toggle a like/dislike from a program card — unlinked airings
         *     lazily resolve their canonical Show via ensure_show() (the same
         *     dedup path backfill_program_shows uses), so every card is
         *     reactable. Session-auth.
         */
        post: operations["tv_programs_api_react_to_program"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/ads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ads Table
         * @description Ads table page — mirrors the four retired *_ads_table views.
         *     Rent tables filter on monthly_price_per_sqm, sale tables on
         *     price_per_sqm (the template's '€/m² min/max' inputs).
         */
        get: operations["classified_ads_api_ads_table"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/regions/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Region Config
         * @description Region-config page read — mirrors the GET half of the retired
         *     apartment/house_region_config views. The house set is keyed off
         *     the '/homes-summer-residences/' URL substring, not the category
         *     column — identical to the old views.
         */
        get: operations["classified_ads_api_region_config"];
        put?: never;
        /**
         * Save Region Config
         * @description Save checked regions — session-auth replacement for the two
         *     retired config POST forms. Same semantics as the views: the kind's
         *     region set is first disabled wholesale, then every submitted URL
         *     is re-enabled (a submitted URL outside the kind's set is enabled
         *     too — verbatim from the old form handler).
         */
        post: operations["classified_ads_api_save_region_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/regions/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Region Stats
         * @description Region stats page — mirrors apartment/house_region_stats.
         *     `regions` repeats per checked parent region; results stay null
         *     until at least one is selected.
         */
        get: operations["classified_ads_api_region_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/regions/{region_id}/children/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Region Stats Children
         * @description Sub-region stats for one parent — mirrors the retired
         *     *_region_stats_children views (404 unless the region is a
         *     parent).
         */
        get: operations["classified_ads_api_region_stats_children"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/regions/{region_id}/ads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Region Ads List
         * @description Ads in a region subtree — mirrors the retired *_region_ads_list
         *     views: the subtree filter is first_seen inside the window, and a
         *     missing/blank deal_type yields an empty table.
         */
        get: operations["classified_ads_api_region_ads_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/sightings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily Sightings
         * @description Daily sightings report — mirrors the retired
         *     daily_sightings_report view: per-day sighting counts for each of
         *     the four ad tables, optionally restricted to a region subtree.
         */
        get: operations["classified_ads_api_daily_sightings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/properties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Property List
         * @description Property list — mirrors the retired property_list view:
         *     properties with their linked-ad counts, district/street filters.
         */
        get: operations["classified_ads_api_property_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classified-ads/properties/{kind}/{pk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Property Detail
         * @description Property detail — mirrors the retired property_detail view,
         *     including linked_ads() (all_objects: hidden and misclassified ads
         *     still belong to the property) and the days_on_market union count.
         */
        get: operations["classified_ads_api_property_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description Dashboard payload — mirrors the retired dashboard view's GET
         *     logic verbatim (defaults fill in when a bound is absent).
         */
        get: operations["scrape_jobs_api_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * VacanciesOut
         * @description One page of vacancies plus the filter option lists the page
         *     needs — a single fat endpoint per the rewrite plan.
         */
        VacanciesOut: {
            /** Vacancies */
            vacancies: components["schemas"]["VacancyOut"][];
            /** Page */
            page: number;
            /** Num Pages */
            num_pages: number;
            /** Total Count */
            total_count: number;
            /** Start Index */
            start_index: number;
            /** End Index */
            end_index: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Keywords */
            keywords: string[];
            /** Industries */
            industries: string[];
        };
        /** VacancyOut */
        VacancyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Company Id */
            company_id: string | null;
            /** Company Name */
            company_name: string | null;
            /** Salary From */
            salary_from: number | null;
            /** Salary To */
            salary_to: number | null;
            /** Application Deadline */
            application_deadline: string | null;
            /** Last Seen */
            last_seen: string | null;
            /** Days Open */
            days_open: number | null;
            /** Keywords */
            keywords: string[];
            /** Industries */
            industries: string[];
        };
        /** CompaniesOut */
        CompaniesOut: {
            /** Companies */
            companies: components["schemas"]["CompanyOut"][];
            /** Page */
            page: number;
            /** Num Pages */
            num_pages: number;
            /** Total Count */
            total_count: number;
            /** Start Index */
            start_index: number;
            /** End Index */
            end_index: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Query */
            query: string;
        };
        /** CompanyIdentityOut */
        CompanyIdentityOut: {
            /** Source */
            source: string;
            /** Employer Id */
            employer_id: number;
            /** Portal Url */
            portal_url: string | null;
        };
        /** CompanyOut */
        CompanyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Reg Code */
            reg_code: string | null;
            /** About */
            about: string | null;
            /** Webpage Url */
            webpage_url: string | null;
            /** Needs Review */
            needs_review: boolean;
            /** Vacancy Count */
            vacancy_count: number;
            /** Open Count */
            open_count: number;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Identities */
            identities: components["schemas"]["CompanyIdentityOut"][];
        };
        /** CompanyDetailOut */
        CompanyDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Reg Code */
            reg_code: string | null;
            /** Reg Code Country */
            reg_code_country: string | null;
            /** About */
            about: string | null;
            /** Webpage Url */
            webpage_url: string | null;
            /** Video Url */
            video_url: string | null;
            /** Applying Url */
            applying_url: string | null;
            /** Address */
            address: string | null;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Contact Phone */
            contact_phone: string | null;
            /** Needs Review */
            needs_review: boolean;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Logo Url */
            logo_url: string | null;
            /** Cover Url */
            cover_url: string | null;
            /** Gallery Urls */
            gallery_urls: (string | null)[];
            /** Identities */
            identities: components["schemas"]["CompanyIdentityOut"][];
            /** Name Aliases */
            name_aliases: string[];
            /** Reg Aliases */
            reg_aliases: string[];
            /** Vacancies */
            vacancies: components["schemas"]["CompanyVacancyOut"][];
            /** Page */
            page: number;
            /** Num Pages */
            num_pages: number;
            /** Total Count */
            total_count: number;
            /** Start Index */
            start_index: number;
            /** End Index */
            end_index: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
        };
        /**
         * CompanyVacancyOut
         * @description Lean vacancy row for the company detail table — no M2M
         *     columns, matching the template's columns.
         */
        CompanyVacancyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Salary From */
            salary_from: number | null;
            /** Salary To */
            salary_to: number | null;
            /** Application Deadline */
            application_deadline: string | null;
            /** Last Seen */
            last_seen: string | null;
        };
        /** KeywordSavedOut */
        KeywordSavedOut: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** KeywordIn */
        KeywordIn: {
            /** Name */
            name: string;
            /**
             * Only Filter
             * @default true
             */
            only_filter: boolean;
        };
        /**
         * ProgramFiltersOut
         * @description Effective filter state — echoes the template's context
         *     `filters` dict so the SPA can render the applied window.
         */
        ProgramFiltersOut: {
            /** Content Rating */
            content_rating: string | null;
            /** Not Content Rating */
            not_content_rating: string | null;
            /** Rating Value */
            rating_value: number | null;
            /** Ratio */
            ratio: number | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Channel Name */
            channel_name: string | null;
            /** Exclude Channel Name */
            exclude_channel_name: string | null;
            /** Show Disliked */
            show_disliked: boolean;
        };
        /** ProgramOut */
        ProgramOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Lv */
            title_lv: string;
            /** Title Eng */
            title_eng: string | null;
            /** Description Lv */
            description_lv: string | null;
            /** Channel Name */
            channel_name: string;
            /** Start Time */
            start_time: string;
            /** Image Url */
            image_url: string | null;
            /** Url */
            url: string | null;
            /** Pg Rating */
            pg_rating: string | null;
            /** Imdb Rating */
            imdb_rating: string | null;
            /** Title Match Ratio */
            title_match_ratio: number;
            show: components["schemas"]["ShowRef"] | null;
            /** User Reaction */
            user_reaction: string | null;
        };
        /**
         * ProgramsOut
         * @description The whole program_list page payload — filtered programs plus
         *     the channel option list (the template's `channels` context).
         */
        ProgramsOut: {
            /** Programs */
            programs: components["schemas"]["ProgramOut"][];
            /** Channels */
            channels: string[];
            filters: components["schemas"]["ProgramFiltersOut"];
        };
        /**
         * ShowRef
         * @description The canonical Show slice a program card needs.
         */
        ShowRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Lv */
            title_lv: string;
            /** Title Eng */
            title_eng: string | null;
            /** Imdb Rating */
            imdb_rating: string | null;
            /** Imdb Url */
            imdb_url: string | null;
            /** Pg Rating */
            pg_rating: string | null;
            /** Image Url */
            image_url: string | null;
            /** Title Match Ratio */
            title_match_ratio: number;
        };
        /** SpokiPageOut */
        SpokiPageOut: {
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** ReactionOut */
        ReactionOut: {
            /** Success */
            success: boolean;
            /**
             * Show Id
             * Format: uuid
             */
            show_id: string;
            /** Reaction */
            reaction: string | null;
            /** Message */
            message: string;
        };
        /**
         * AdOut
         * @description One row of an ads table — the union of the apartment and house
         *     columns the templates render (kind-specific fields stay null).
         */
        AdOut: {
            /** Id */
            id: number;
            /** Ad Id */
            ad_id: string;
            /** Link */
            link: string;
            /** District */
            district: string;
            /** Street Name */
            street_name: string;
            /** Street No */
            street_no: string;
            /** Rooms */
            rooms: number;
            /** Size */
            size: number;
            /** Post Date */
            post_date: string | null;
            /** Days Active */
            days_active: number;
            /** Deal */
            deal: string;
            /** Project */
            project: string | null;
            /** Floor */
            floor: number | null;
            /** Max Floor */
            max_floor: number | null;
            /** Floors */
            floors: number | null;
            /** Land Area Sqm */
            land_area_sqm: number | null;
            /** Price Per Sqm */
            price_per_sqm: number;
            /** Total Price */
            total_price: number;
            /** Monthly Price */
            monthly_price: number | null;
            /** Monthly Price Per Sqm */
            monthly_price_per_sqm: number | null;
        };
        /**
         * AdsFiltersOut
         * @description Echo of the applied filters — the template's selected_* context.
         */
        AdsFiltersOut: {
            /** District */
            district: string;
            /** Rooms */
            rooms: number | null;
            /** Price Min */
            price_min: number | null;
            /** Price Max */
            price_max: number | null;
        };
        /**
         * AdsTableOut
         * @description One page of an ads table plus the filter option lists — a
         *     single fat endpoint per the rewrite plan.
         */
        AdsTableOut: {
            /** Ads */
            ads: components["schemas"]["AdOut"][];
            /** Page */
            page: number;
            /** Num Pages */
            num_pages: number;
            /** Total Count */
            total_count: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Districts */
            districts: string[];
            /** Room Choices */
            room_choices: number[];
            filters: components["schemas"]["AdsFiltersOut"];
        };
        /** RegionConfigOut */
        RegionConfigOut: {
            /** Kind */
            kind: string;
            /** Regions Tree */
            regions_tree: components["schemas"]["RegionNodeOut"][];
            /** Enabled Count */
            enabled_count: number;
            /** Total Count */
            total_count: number;
        };
        /**
         * RegionNodeOut
         * @description A region with its sub-regions — the config/checkbox trees.
         */
        RegionNodeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Scrape Enabled */
            scrape_enabled: boolean;
            /** Sub Regions */
            sub_regions: components["schemas"]["RegionNodeOut"][];
        };
        /** RegionConfigSavedOut */
        RegionConfigSavedOut: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** RegionConfigIn */
        RegionConfigIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "apartment" | "house";
            /** Regions */
            regions?: string[];
        };
        /** RegionRefOut */
        RegionRefOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** RegionStatsOut */
        RegionStatsOut: {
            /** Kind */
            kind: string;
            /** Parent Regions */
            parent_regions: components["schemas"]["RegionRefOut"][];
            /** Selected Ids */
            selected_ids: number[];
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Deal Type */
            deal_type: string;
            /** Results */
            results: components["schemas"]["RegionStatsRowOut"][] | null;
        };
        /**
         * RegionStatsRowOut
         * @description One row of the region-stats table — a dict from
         *     _compute_*_region_stats with the Region nested under 'region'.
         */
        RegionStatsRowOut: {
            region: components["schemas"]["RegionRefOut"];
            /** Total Ads */
            total_ads: number;
            /** Total Properties */
            total_properties: number;
            /** Avg Price Per Sqm */
            avg_price_per_sqm: number | null;
            /** Avg Size */
            avg_size: number | null;
            /** Avg Days Tracked */
            avg_days_tracked: number | null;
            /** Avg Days On Market */
            avg_days_on_market: number | null;
        };
        /** RegionStatsChildrenOut */
        RegionStatsChildrenOut: {
            /** Kind */
            kind: string;
            parent_region: components["schemas"]["RegionRefOut"];
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Deal Type */
            deal_type: string;
            /** Results */
            results: components["schemas"]["RegionStatsRowOut"][];
        };
        /** RegionAdsOut */
        RegionAdsOut: {
            /** Kind */
            kind: string;
            region: components["schemas"]["RegionAdsRegionOut"];
            /** Ads */
            ads: components["schemas"]["AdOut"][];
            /** Page */
            page: number;
            /** Num Pages */
            num_pages: number;
            /** Total Count */
            total_count: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Deal Type */
            deal_type: string;
        };
        /** RegionAdsRegionOut */
        RegionAdsRegionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            /** Parent Name */
            parent_name: string | null;
        };
        /** DailySightingsOut */
        DailySightingsOut: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Order */
            order: string;
            /** Selected Region */
            selected_region: number | null;
            /** Daily Data */
            daily_data: components["schemas"]["DailySightingsRowOut"][];
            /** Regions */
            regions: components["schemas"]["SightingsRegionOut"][];
        };
        /** DailySightingsRowOut */
        DailySightingsRowOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Apartment Rent */
            apartment_rent: number;
            /** Apartment Sale */
            apartment_sale: number;
            /** Apartment Total */
            apartment_total: number;
            /** House Rent */
            house_rent: number;
            /** House Sale */
            house_sale: number;
            /** House Total */
            house_total: number;
            /** Grand Total */
            grand_total: number;
        };
        /**
         * SightingsRegionOut
         * @description Parent region + flat sub-region list — the <optgroup> option
         *     tree of the retired sightings form.
         */
        SightingsRegionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Sub Regions */
            sub_regions: components["schemas"]["RegionRefOut"][];
        };
        /** PropertyListOut */
        PropertyListOut: {
            /** Kind */
            kind: string;
            /** Kind Label */
            kind_label: string;
            /** Properties */
            properties: components["schemas"]["PropertyRowOut"][];
            /** Page */
            page: number;
            /** Num Pages */
            num_pages: number;
            /** Total Count */
            total_count: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Districts */
            districts: string[];
            /** Selected District */
            selected_district: string;
            /** Selected Street */
            selected_street: string;
        };
        /** PropertyRowOut */
        PropertyRowOut: {
            /** Id */
            id: number;
            /** District */
            district: string;
            /** Street Name */
            street_name: string;
            /** Street No */
            street_no: string;
            /** Apartment No */
            apartment_no: string | null;
            /** Rooms */
            rooms: number;
            /** Size */
            size: number;
            /** Rent Ad Count */
            rent_ad_count: number;
            /** Sale Ad Count */
            sale_ad_count: number;
            /**
             * First Seen
             * Format: date
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
        };
        /**
         * LinkedAdOut
         * @description One row of the property-detail linked-ads table — built from
         *     both the rent and sale ad models (all_objects via linked_ads).
         */
        LinkedAdOut: {
            /** Ad Id */
            ad_id: string;
            /** Link */
            link: string;
            /** Deal */
            deal: string;
            /** Price */
            price: number | null;
            /** Price Suffix */
            price_suffix: string;
            /** Match Status */
            match_status: string;
            /** Match Score */
            match_score: number | null;
            /**
             * First Seen
             * Format: date
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
            /** Days Active */
            days_active: number;
        };
        /** PropertyDetailOut */
        PropertyDetailOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Kind Label */
            kind_label: string;
            /** District */
            district: string;
            /** Street Name */
            street_name: string;
            /** Street No */
            street_no: string;
            /** Apartment No */
            apartment_no: string | null;
            /** Region Name */
            region_name: string | null;
            /** Rooms */
            rooms: number;
            /** Size */
            size: number;
            /** Floor */
            floor: number | null;
            /** Max Floor */
            max_floor: number | null;
            /** Floors */
            floors: number | null;
            /** Land Area Sqm */
            land_area_sqm: number | null;
            /** Days On Market */
            days_on_market: number;
            /**
             * First Seen
             * Format: date
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
            /** Ad Rows */
            ad_rows: components["schemas"]["LinkedAdOut"][];
        };
        /**
         * DashboardOut
         * @description The whole dashboard page payload — one fat GET per the
         *     rewrite plan (jobs table + daily table + filter echo).
         */
        DashboardOut: {
            /** Jobs */
            jobs: components["schemas"]["JobRowOut"][];
            /** Rows */
            rows: components["schemas"]["DayRowOut"][];
            totals: components["schemas"]["RunTotalsOut"];
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
        };
        /**
         * DayRowOut
         * @description One day x job row — a dict from usage.runs_by_day().
         */
        DayRowOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Job Slug */
            job_slug: string;
            /** Run Count */
            run_count: number;
            /** Success Count */
            success_count: number;
            /** Partial Count */
            partial_count: number;
            /** Failed Count */
            failed_count: number;
            /** Abandoned Count */
            abandoned_count: number;
            /** Avg Duration Seconds */
            avg_duration_seconds: number | null;
        };
        /**
         * JobRefOut
         * @description The ScrapeJob slice a jobs-table row needs.
         */
        JobRefOut: {
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Is Enabled */
            is_enabled: boolean;
        };
        /**
         * JobRowOut
         * @description One jobs-table row — a dict from usage.job_overview().
         */
        JobRowOut: {
            job: components["schemas"]["JobRefOut"];
            /** Cycle Key */
            cycle_key: string | null;
            /** Item Total */
            item_total: number;
            /** Item Active */
            item_active: number;
            /** Cycle Done */
            cycle_done: number;
            /** Cycle Failed */
            cycle_failed: number;
            /** Progress Pct */
            progress_pct: number | null;
            /** Running */
            running: boolean;
            last_run: components["schemas"]["LastRunOut"] | null;
        };
        /**
         * LastRunOut
         * @description A job's most recent run — the status/last-run/duration cells.
         */
        LastRunOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Executed By */
            executed_by: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
        };
        /**
         * RunTotalsOut
         * @description The daily-runs subtitle totals — a usage.run_totals() dict.
         */
        RunTotalsOut: {
            /** Run Count */
            run_count: number;
            /** Success Count */
            success_count: number;
            /** Partial Count */
            partial_count: number;
            /** Failed Count */
            failed_count: number;
            /** Abandoned Count */
            abandoned_count: number;
            /** Avg Duration Seconds */
            avg_duration_seconds: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    fetcher_api_list_vacancies: {
        parameters: {
            query?: {
                include_keywords?: string[];
                exclude_keywords?: string[];
                include_industries?: string[];
                show_active_only?: boolean;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacanciesOut"];
                };
            };
        };
    };
    fetcher_api_list_companies: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesOut"];
                };
            };
        };
    };
    fetcher_api_company_detail: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailOut"];
                };
            };
        };
    };
    fetcher_api_add_keyword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordSavedOut"];
                };
            };
        };
    };
    tv_programs_api_list_programs: {
        parameters: {
            query?: {
                content_rating?: string | null;
                not_content_rating?: string | null;
                rating_value?: number | null;
                ratio?: number | null;
                start_date?: string | null;
                end_date?: string | null;
                channel?: string | null;
                exclude_channel?: string | null;
                show_disliked?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramsOut"];
                };
            };
        };
    };
    tv_programs_api_spoki_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpokiPageOut"];
                };
            };
        };
    };
    tv_programs_api_react_to_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                show_id: string;
                reaction: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionOut"];
                };
            };
        };
    };
    tv_programs_api_react_to_program: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
                reaction: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionOut"];
                };
            };
        };
    };
    classified_ads_api_ads_table: {
        parameters: {
            query: {
                kind: "apartment" | "house";
                deal: "rent" | "sale";
                district?: string;
                rooms?: number | null;
                price_min?: number | null;
                price_max?: number | null;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdsTableOut"];
                };
            };
        };
    };
    classified_ads_api_region_config: {
        parameters: {
            query: {
                kind: "apartment" | "house";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionConfigOut"];
                };
            };
        };
    };
    classified_ads_api_save_region_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionConfigIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionConfigSavedOut"];
                };
            };
        };
    };
    classified_ads_api_region_stats: {
        parameters: {
            query: {
                kind: "apartment" | "house";
                date_from?: string | null;
                date_to?: string | null;
                deal_type?: string;
                regions?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionStatsOut"];
                };
            };
        };
    };
    classified_ads_api_region_stats_children: {
        parameters: {
            query: {
                kind: "apartment" | "house";
                date_from?: string | null;
                date_to?: string | null;
                deal_type?: string;
            };
            header?: never;
            path: {
                region_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionStatsChildrenOut"];
                };
            };
        };
    };
    classified_ads_api_region_ads_list: {
        parameters: {
            query: {
                kind: "apartment" | "house";
                date_from?: string | null;
                date_to?: string | null;
                deal_type?: string;
                page?: number;
            };
            header?: never;
            path: {
                region_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionAdsOut"];
                };
            };
        };
    };
    classified_ads_api_daily_sightings: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                order?: string;
                region?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailySightingsOut"];
                };
            };
        };
    };
    classified_ads_api_property_list: {
        parameters: {
            query: {
                kind: "apartment" | "house";
                district?: string;
                street?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyListOut"];
                };
            };
        };
    };
    classified_ads_api_property_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetailOut"];
                };
            };
        };
    };
    scrape_jobs_api_dashboard: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
}
