# Generated by Django 5.2.8 on 2026-09-30 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('text', models.TextField()),
                ('chars', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_input',
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('declared_roles', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_requests_per_run', models.PositiveIntegerField(blank=True, null=True)),
                ('max_requests_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('store_inputs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_job',
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai_compatible', 'OpenAI-compatible')], max_length=30)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_setting', models.CharField(max_length=100)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=60)),
                ('max_retries', models.PositiveSmallIntegerField(default=2)),
                ('backoff_base_seconds', models.FloatField(default=2.0)),
                ('min_request_interval_seconds', models.FloatField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_provider',
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_prompt_template',
                'unique_together': {('key', 'sha256')},
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('auto_registered', models.BooleanField(default=False)),
                ('supports_json_mode', models.BooleanField(default=False)),
                ('input_price_per_mtok', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('output_price_per_mtok', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('context_length', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ai_providers.aiprovider')),
            ],
            options={
                'db_table': 'ai_model',
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AIJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ai_providers.aijob')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='ai_providers.aimodel')),
            ],
            options={
                'db_table': 'ai_job_model',
                'ordering': ['job', 'role', 'priority', 'id'],
                'unique_together': {('job', 'role', 'model')},
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('attempt', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('blocked', 'Blocked'), ('error', 'Error')], max_length=20)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('finish_reason', models.CharField(blank=True, max_length=50)),
                ('block_reason', models.CharField(blank=True, max_length=200)),
                ('input_tokens', models.PositiveIntegerField(null=True)),
                ('output_tokens', models.PositiveIntegerField(null=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('latency_ms', models.PositiveIntegerField(null=True)),
                ('prompt_layout', models.CharField(max_length=30)),
                ('options', models.JSONField(default=dict)),
                ('prompt_chars', models.PositiveIntegerField()),
                ('prompt_sha256', models.CharField(max_length=64)),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='ai_providers.aiinput')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='ai_providers.aijob')),
                ('prompt_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='ai_providers.aiprompttemplate')),
                ('requested_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai_providers.aimodel')),
                ('served_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai_providers.aimodel')),
            ],
            options={
                'db_table': 'ai_request',
                'indexes': [models.Index(fields=['job', 'created_at'], name='ai_request_job_id_07a26d_idx'), models.Index(fields=['requested_model', 'created_at'], name='ai_request_request_6e38cc_idx')],
            },
        ),
    ]
