# Generated by Django 5.2.8 on 2026-07-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, unique=True)),
                ('deal_type', models.CharField(choices=[('RENT', 'Rent'), ('SELL', 'Sell')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('link', models.URLField(max_length=500)),
                ('district', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('street_no', models.CharField(blank=True, max_length=50)),
                ('rooms', models.IntegerField()),
                ('size', models.FloatField(help_text='Square metres')),
                ('floor', models.IntegerField()),
                ('max_floor', models.IntegerField()),
                ('project', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(null=True)),
                ('price_per_sqm', models.FloatField()),
                ('alt_price_per_sqm', models.FloatField()),
                ('total_price', models.FloatField()),
                ('alt_price', models.FloatField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
