# Generated by Django 5.2.8 on 2026-07-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedAdSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_on', models.DateField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='classified_ads.classifiedad')),
            ],
            options={
                'unique_together': {('ad', 'seen_on')},
            },
        ),
    ]
