# Generated by Django 5.2.8 on 2026-07-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0002_add_classified_ad_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='contact_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
