# Generated by Django 5.2.8 on 2026-07-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0004_add_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contact_id', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='classifiedad',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='classifiedad',
            name='phone',
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='classified_ads.seller'),
        ),
    ]
