# Generated by Django 5.2.8 on 2026-07-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0005_seller_remove_classifiedad_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='facilities',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='house_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
