# Generated by Django 4.2.6 on 2026-07-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0006_classifiedad_facilities_classifiedad_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('link', models.URLField(max_length=500)),
                ('region_name', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('street_no', models.CharField(blank=True, max_length=50)),
                ('rooms', models.IntegerField()),
                ('size', models.FloatField(help_text='Square metres')),
                ('floor', models.IntegerField()),
                ('max_floor', models.IntegerField()),
                ('project', models.CharField(max_length=255)),
                ('house_type', models.CharField(blank=True, max_length=255)),
                ('facilities', models.CharField(blank=True, max_length=500)),
                ('post_date', models.DateTimeField(null=True)),
                ('price_per_sqm', models.FloatField()),
                ('total_price', models.FloatField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('monthly_price', models.FloatField()),
                ('monthly_price_per_sqm', models.FloatField()),
                ('total_price_120m', models.FloatField()),
                ('price_per_sqm_120m', models.FloatField()),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ads', to='classified_ads.region')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ads', to='classified_ads.seller')),
            ],
            options={
                'verbose_name': 'Apartment for Rent',
                'verbose_name_plural': 'Apartments for Rent',
                'db_table': 'classified_ads_apartment_rent',
            },
        ),
        migrations.CreateModel(
            name='ApartmentForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('link', models.URLField(max_length=500)),
                ('region_name', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('street_no', models.CharField(blank=True, max_length=50)),
                ('rooms', models.IntegerField()),
                ('size', models.FloatField(help_text='Square metres')),
                ('floor', models.IntegerField()),
                ('max_floor', models.IntegerField()),
                ('project', models.CharField(max_length=255)),
                ('house_type', models.CharField(blank=True, max_length=255)),
                ('facilities', models.CharField(blank=True, max_length=500)),
                ('post_date', models.DateTimeField(null=True)),
                ('price_per_sqm', models.FloatField()),
                ('total_price', models.FloatField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ads', to='classified_ads.region')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ads', to='classified_ads.seller')),
            ],
            options={
                'verbose_name': 'Apartment for Sale',
                'verbose_name_plural': 'Apartments for Sale',
                'db_table': 'classified_ads_apartment_sale',
            },
        ),
        migrations.CreateModel(
            name='ApartmentForSaleSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_on', models.DateField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='classified_ads.apartmentforsale')),
            ],
            options={
                'db_table': 'classified_ads_apartment_sale_sighting',
                'unique_together': {('ad', 'seen_on')},
            },
        ),
        migrations.CreateModel(
            name='ApartmentForRentSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_on', models.DateField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='classified_ads.apartmentforrent')),
            ],
            options={
                'db_table': 'classified_ads_apartment_rent_sighting',
                'unique_together': {('ad', 'seen_on')},
            },
        ),
    ]
