# Generated by Django 4.2.6 on 2026-07-13 14:04

from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    ClassifiedAd = apps.get_model('classified_ads', 'ClassifiedAd')
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    ApartmentForSale = apps.get_model('classified_ads', 'ApartmentForSale')
    ClassifiedAdSighting = apps.get_model(
        'classified_ads', 'ClassifiedAdSighting'
    )
    ApartmentForRentSighting = apps.get_model(
        'classified_ads', 'ApartmentForRentSighting'
    )
    ApartmentForSaleSighting = apps.get_model(
        'classified_ads', 'ApartmentForSaleSighting'
    )

    for ad in ClassifiedAd.objects.filter(deal_type='RENT'):
        new_ad = ApartmentForRent.objects.create(
            ad_id=ad.ad_id,
            comment=ad.comment,
            link=ad.link,
            region=ad.region,
            region_name=ad.region_name,
            district=ad.district,
            street_name=ad.street_name,
            street_no=ad.street_no,
            rooms=ad.rooms,
            size=ad.size,
            floor=ad.floor,
            max_floor=ad.max_floor,
            project=ad.project,
            house_type=ad.house_type,
            facilities=ad.facilities,
            post_date=ad.post_date,
            seller=ad.seller,
            price_per_sqm=ad.price_per_sqm,
            total_price=ad.total_price,
            first_seen=ad.first_seen,
            last_seen=ad.last_seen,
            monthly_price=ad.total_price,
            monthly_price_per_sqm=ad.price_per_sqm,
            total_price_120m=ad.alt_price,
            price_per_sqm_120m=ad.alt_price_per_sqm,
        )

        for sighting in ClassifiedAdSighting.objects.filter(ad=ad):
            ApartmentForRentSighting.objects.create(
                ad=new_ad,
                seen_on=sighting.seen_on,
            )

    for ad in ClassifiedAd.objects.filter(deal_type='SELL'):
        new_ad = ApartmentForSale.objects.create(
            ad_id=ad.ad_id,
            comment=ad.comment,
            link=ad.link,
            region=ad.region,
            region_name=ad.region_name,
            district=ad.district,
            street_name=ad.street_name,
            street_no=ad.street_no,
            rooms=ad.rooms,
            size=ad.size,
            floor=ad.floor,
            max_floor=ad.max_floor,
            project=ad.project,
            house_type=ad.house_type,
            facilities=ad.facilities,
            post_date=ad.post_date,
            seller=ad.seller,
            price_per_sqm=ad.price_per_sqm,
            total_price=ad.total_price,
            first_seen=ad.first_seen,
            last_seen=ad.last_seen,
        )

        for sighting in ClassifiedAdSighting.objects.filter(ad=ad):
            ApartmentForSaleSighting.objects.create(
                ad=new_ad,
                seen_on=sighting.seen_on,
            )


def migrate_data_backward(apps, schema_editor):
    ClassifiedAd = apps.get_model('classified_ads', 'ClassifiedAd')
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    ApartmentForSale = apps.get_model('classified_ads', 'ApartmentForSale')
    ClassifiedAdSighting = apps.get_model(
        'classified_ads', 'ClassifiedAdSighting'
    )
    ApartmentForRentSighting = apps.get_model(
        'classified_ads', 'ApartmentForRentSighting'
    )
    ApartmentForSaleSighting = apps.get_model(
        'classified_ads', 'ApartmentForSaleSighting'
    )

    for ad in ApartmentForRent.objects.all():
        old_ad = ClassifiedAd.objects.create(
            ad_id=ad.ad_id,
            deal_type='RENT',
            comment=ad.comment,
            link=ad.link,
            region=ad.region,
            region_name=ad.region_name,
            district=ad.district,
            street_name=ad.street_name,
            street_no=ad.street_no,
            rooms=ad.rooms,
            size=ad.size,
            floor=ad.floor,
            max_floor=ad.max_floor,
            project=ad.project,
            house_type=ad.house_type,
            facilities=ad.facilities,
            post_date=ad.post_date,
            seller=ad.seller,
            price_per_sqm=ad.monthly_price_per_sqm,
            total_price=ad.monthly_price,
            alt_price=ad.total_price_120m,
            alt_price_per_sqm=ad.price_per_sqm_120m,
            first_seen=ad.first_seen,
            last_seen=ad.last_seen,
        )

        for sighting in ApartmentForRentSighting.objects.filter(ad=ad):
            ClassifiedAdSighting.objects.create(
                ad=old_ad,
                seen_on=sighting.seen_on,
            )

    for ad in ApartmentForSale.objects.all():
        old_ad = ClassifiedAd.objects.create(
            ad_id=ad.ad_id,
            deal_type='SELL',
            comment=ad.comment,
            link=ad.link,
            region=ad.region,
            region_name=ad.region_name,
            district=ad.district,
            street_name=ad.street_name,
            street_no=ad.street_no,
            rooms=ad.rooms,
            size=ad.size,
            floor=ad.floor,
            max_floor=ad.max_floor,
            project=ad.project,
            house_type=ad.house_type,
            facilities=ad.facilities,
            post_date=ad.post_date,
            seller=ad.seller,
            price_per_sqm=ad.price_per_sqm,
            total_price=ad.total_price,
            alt_price=0.0,
            alt_price_per_sqm=0.0,
            first_seen=ad.first_seen,
            last_seen=ad.last_seen,
        )

        for sighting in ApartmentForSaleSighting.objects.filter(ad=ad):
            ClassifiedAdSighting.objects.create(
                ad=old_ad,
                seen_on=sighting.seen_on,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0007_add_apartment_rent_sale_models'),
    ]

    operations = [
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
    ]
