# Generated by Django 4.2.6 on 2026-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0008_migrate_data_to_new_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classifiedadsighting',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classifiedadsighting',
            name='ad',
        ),
        migrations.AddField(
            model_name='apartmentforrent',
            name='is_sale_misclassified',
            field=models.BooleanField(default=False, help_text='True if this rental ad is actually a for-sale listing posted in the wrong category'),
        ),
        migrations.DeleteModel(
            name='ClassifiedAd',
        ),
        migrations.DeleteModel(
            name='ClassifiedAdSighting',
        ),
    ]
