# Generated by Django 4.2.6 on 2026-07-30 11:13

from django.db import migrations


def populate_is_sale_misclassified(apps, schema_editor):
    """
    Flag misclassified for-sale ads in the rental table using Strategy C+.
    
    Two complementary signals:
    1. Price signal: monthly_price_per_sqm > 50 (sale price entered as rent)
    2. Keyword signal: Latvian/Russian sale vocabulary in comment field
    
    Expected: ~568 records flagged out of ~3,476 total.
    See: docs/misclassified_sale_ads_analysis.md
    """
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    
    PRICE_THRESHOLD = 50
    SALE_KEYWORDS = [
        '%pārdod%', '%pārdošan%', '%pārdots%', '%izpirkum%', '%pirkt%',
        '%pardod%', '%pardosan%', '%pardots%',
        '%продаётся%', '%Продаем%', '%Продается%', '%Продам%',
    ]
    
    from django.db.models import Q
    
    keyword_filter = Q()
    for kw in SALE_KEYWORDS:
        keyword_filter |= Q(comment__icontains=kw.strip('%'))
    
    price_filter = Q(monthly_price_per_sqm__gt=PRICE_THRESHOLD)
    
    updated_count = ApartmentForRent.objects.filter(
        price_filter | keyword_filter
    ).update(is_sale_misclassified=True)
    
    print(f"Flagged {updated_count} misclassified sale ads")


def reverse_populate(apps, schema_editor):
    """Reset all flags to False."""
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    ApartmentForRent.objects.all().update(is_sale_misclassified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0009_alter_classifiedadsighting_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_is_sale_misclassified,
            reverse_populate
        ),
    ]
