# Generated by Django 4.2.6 on 2026-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0013_add_region_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentforrent',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentforsale',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseforrent',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
