# Generated by Django 4.2.6 on 2026-08-19 10:48

from django.db import migrations
from django.utils import timezone
from datetime import datetime


def hide_old_entries(apps, schema_editor):
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    ApartmentForSale = apps.get_model('classified_ads', 'ApartmentForSale')
    HouseForRent = apps.get_model('classified_ads', 'HouseForRent')
    HouseForSale = apps.get_model('classified_ads', 'HouseForSale')
    
    cutoff_date = timezone.make_aware(datetime(2026, 8, 11))
    
    apartment_rent_count = ApartmentForRent.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=True)
    
    apartment_sale_count = ApartmentForSale.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=True)
    
    house_rent_count = HouseForRent.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=True)
    
    house_sale_count = HouseForSale.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=True)
    
    print(f"Hidden {apartment_rent_count} apartment rental ads")
    print(f"Hidden {apartment_sale_count} apartment sale ads")
    print(f"Hidden {house_rent_count} house rental ads")
    print(f"Hidden {house_sale_count} house sale ads")


def unhide_entries(apps, schema_editor):
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    ApartmentForSale = apps.get_model('classified_ads', 'ApartmentForSale')
    HouseForRent = apps.get_model('classified_ads', 'HouseForRent')
    HouseForSale = apps.get_model('classified_ads', 'HouseForSale')
    
    cutoff_date = timezone.make_aware(datetime(2026, 8, 11))
    
    ApartmentForRent.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=False)
    
    ApartmentForSale.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=False)
    
    HouseForRent.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=False)
    
    HouseForSale.objects.filter(
        first_seen__lt=cutoff_date
    ).update(is_hidden=False)


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0014_add_is_hidden_field'),
    ]

    operations = [
        migrations.RunPython(hide_old_entries, unhide_entries),
    ]
