# Generated by Django 4.2.6 on 2026-08-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0015_hide_entries_before_2026_08_11'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentforrent',
            old_name='project',
            new_name='project_raw',
        ),
        migrations.RenameField(
            model_name='apartmentforsale',
            old_name='project',
            new_name='project_raw',
        ),
    ]
