# Generated by Django 4.2.6 on 2026-08-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0016_rename_project_to_project_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='apartmentforrent',
            name='project_raw',
            field=models.CharField(help_text='Original project value from source', max_length=255),
        ),
        migrations.AlterField(
            model_name='apartmentforsale',
            name='project_raw',
            field=models.CharField(help_text='Original project value from source', max_length=255),
        ),
        migrations.AddField(
            model_name='apartmentforrent',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Standardized project type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_ads', to='classified_ads.project'),
        ),
        migrations.AddField(
            model_name='apartmentforsale',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Standardized project type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_ads', to='classified_ads.project'),
        ),
    ]
