# Generated by Django 4.2.6 on 2026-08-19 11:47

from django.db import migrations


def backfill_projects(apps, schema_editor):
    Project = apps.get_model('classified_ads', 'Project')
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    ApartmentForSale = apps.get_model('classified_ads', 'ApartmentForSale')
    
    PROJECT_MAPPINGS = {
        '103-th': 'Series 103',
        '103.': 'Series 103',
        '602-th': 'Series 602',
        '602.': 'Series 602',
        '467-th': 'Series 467',
        '467.': 'Series 467',
        '119-th': 'Series 119',
        '119.': 'Series 119',
        '104-th': 'Series 104',
        '104.': 'Series 104',
        'Spec. pr.': 'Special Project',
        'Specpr.': 'Special Project',
        'Chrusch.': 'Khrushchyovka',
        'Hrušč.': 'Khrushchyovka',
        'Czech pr.': 'Czech Project',
        'Čehu pr.': 'Czech Project',
        'Lit pr.': 'Lithuanian Project',
        'LT proj.': 'Lithuanian Project',
        'Stalin project': 'Stalin Era',
        'Staļina': 'Stalin Era',
        'Recon.': 'Renovated',
        'Renov.': 'Renovated',
        'New': 'New Construction',
        'Jaun.': 'New Construction',
        'Sm.fam.': 'Small Family House',
        'M. ģim.': 'Small Family House',
        'Priv.house': 'Private House',
        'Priv. m.': 'Private House',
        'Pre-war house': 'Pre-War',
        'P. kara': 'Pre-War',
        '-': 'Unknown',
    }
    
    project_cache = {}
    for raw_value, normalized_name in PROJECT_MAPPINGS.items():
        if normalized_name not in project_cache:
            project, _ = Project.objects.get_or_create(
                name=normalized_name
            )
            project_cache[normalized_name] = project
    
    for model in [ApartmentForRent, ApartmentForSale]:
        ads_to_update = []
        for ad in model.objects.all().iterator(chunk_size=1000):
            normalized_name = PROJECT_MAPPINGS.get(ad.project_raw)
            if normalized_name:
                ad.project = project_cache[normalized_name]
                ads_to_update.append(ad)
            
            if len(ads_to_update) >= 1000:
                model.objects.bulk_update(ads_to_update, ['project'])
                ads_to_update = []
        
        if ads_to_update:
            model.objects.bulk_update(ads_to_update, ['project'])


def reverse_backfill(apps, schema_editor):
    ApartmentForRent = apps.get_model('classified_ads', 'ApartmentForRent')
    ApartmentForSale = apps.get_model('classified_ads', 'ApartmentForSale')
    
    for model in [ApartmentForRent, ApartmentForSale]:
        model.objects.all().update(project=None)


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0017_project_alter_apartmentforrent_project_raw_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_projects, reverse_backfill),
    ]
