# Generated by Django 5.2.8 on 2026-09-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0017_add_apartment_no_field'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Project',
                    fields=[
                        ('id', models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name='ID'
                        )),
                        ('name', models.CharField(
                            max_length=100,
                            unique=True
                        )),
                        ('description', models.TextField(blank=True)),
                    ],
                ),
                migrations.AddField(
                    model_name='apartmentforrent',
                    name='project_raw',
                    field=models.CharField(
                        blank=True,
                        help_text='Original project value from source',
                        max_length=255
                    ),
                ),
                migrations.AddField(
                    model_name='apartmentforsale',
                    name='project_raw',
                    field=models.CharField(
                        blank=True,
                        help_text='Original project value from source',
                        max_length=255
                    ),
                ),
                migrations.AlterField(
                    model_name='apartmentforrent',
                    name='project',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Standardized project type',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_ads',
                        to='classified_ads.project'
                    ),
                ),
                migrations.AlterField(
                    model_name='apartmentforsale',
                    name='project',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Standardized project type',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_ads',
                        to='classified_ads.project'
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='region',
            name='order_id',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
