# Generated by Django 5.2.8 on 2026-10-01 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='When off, the runner still records runs/items but never skips completed items — every pass is a full pass.')),
                ('stale_timeout_minutes', models.PositiveIntegerField(default=30, help_text='A RUNNING run whose heartbeat (updated_at) is older than this is marked ABANDONED by the next run of the job.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scrape_job',
            },
        ),
        migrations.CreateModel(
            name='ScrapeJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority items are processed first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scrape_jobs.scrapejob')),
            ],
            options={
                'db_table': 'scrape_job_item',
                'ordering': ['-priority', 'id'],
                'unique_together': {('job', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ScrapeJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_key', models.CharField(db_index=True, help_text='Resume scope — UTC date by default (--cycle).', max_length=50)),
                ('execution_id', models.CharField(db_index=True, help_text='Cloud Run execution+task id, or local-<host>-<pid>.', max_length=200)),
                ('executed_by', models.CharField(choices=[('local', 'Local'), ('gcp_cloud_run', 'GCP Cloud Run')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned'), ('PARTIAL', 'Partial')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Heartbeat — touched at every item checkpoint and between pages inside an item.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scrape_jobs.scrapejob')),
                ('last_completed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scrape_jobs.scrapejobitem')),
            ],
            options={
                'db_table': 'scrape_job_run',
            },
        ),
        migrations.CreateModel(
            name='ScrapeJobRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape_jobs.scrapejobitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scrape_jobs.scrapejobrun')),
            ],
            options={
                'db_table': 'scrape_job_run_item',
            },
        ),
        migrations.AddIndex(
            model_name='scrapejobrun',
            index=models.Index(fields=['job', 'cycle_key'], name='scrape_job__job_id_db8bfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapejobrunitem',
            unique_together={('run', 'item')},
        ),
    ]
