# Generated by Django 4.2.6 on 2024-09-07 03:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('only_filter', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('job_portal_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('salary_from', models.FloatField(null=True)),
                ('salary_to', models.FloatField(null=True)),
                ('url', models.URLField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField(null=True)),
                ('days_open', models.IntegerField(null=True)),
                ('vacancy_portal_id', models.IntegerField(null=True)),
                ('application_deadline', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyContainsKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.keyword')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.vacancy')),
            ],
            options={
                'db_table': 'fetcher_vacancy_contains_keyword',
            },
        ),
    ]
