# Generated by Django 4.2.6 on 2024-07-22 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('job_portal_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('url', models.URLField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('days_open', models.IntegerField()),
                ('vacancy_portal_id', models.IntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
