# Generated by Django 4.2.6 on 2024-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='application_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='days_open',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_portal_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_portal_id',
            field=models.IntegerField(null=True),
        ),
    ]
