# Generated by Django 4.2.6 on 2024-08-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_alter_vacancy_application_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company_id',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
