# Generated by Django 4.2.6 on 2024-08-28 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_remove_vacancy_company_id_vacancy_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyContainsKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.keyword')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.vacancy')),
            ],
        ),
    ]
