# Generated by Django 4.2.6 on 2024-08-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0004_keyword_vacancycontainskeyword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancycontainskeyword',
            table='vacancy_contains_keyword',
        ),
    ]
