# Generated by Django 4.2.6 on 2024-09-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0004_alter_vacancyindustries_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancyindustries',
            table='fetcher_vacancy_industries',
        ),
    ]
