# Generated by Django 4.2.6 on 2024-08-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0005_alter_vacancycontainskeyword_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancycontainskeyword',
            table='fetcher_vacancy_contains_keyword',
        ),
    ]
