# Generated by Django 4.2.6 on 2024-08-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0006_alter_vacancycontainskeyword_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='only_filter',
            field=models.BooleanField(default=False),
        ),
    ]
