# Generated by Django 4.2.6 on 2024-09-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
