# Generated by Django 4.2.6 on 2024-09-21 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_vacancy_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='industry',
        ),
        migrations.CreateModel(
            name='VacancyIndustries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.industry')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='industries',
            field=models.ManyToManyField(through='fetcher.VacancyIndustries', to='fetcher.industry'),
        ),
    ]
