# Generated by Django 4.2.6 on 2024-09-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_industry_remove_vacancy_industry_vacancyindustries_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancyindustries',
            unique_together={('vacancy', 'industry')},
        ),
    ]
