# Generated by Django 5.0.4 on 2025-09-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0006_alter_vacancy_vacancy_portal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_portal_id',
            field=models.IntegerField(help_text='The ID of the vacancy on the job portal', null=True),
        ),
    ]
