# Generated by Django 5.2.8 on 2026-10-02 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0010_vacancy_detail_fetched_at_vacancyfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('reg_code', models.CharField(blank=True, help_text='Normalized registration number — unique where present (unique_company_reg_code)', max_length=64, null=True)),
                ('reg_code_country', models.CharField(blank=True, help_text='Best-effort ISO country of reg_code', max_length=2, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('webpage_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('logo_file_id', models.CharField(blank=True, help_text='files-service file UUID', max_length=64, null=True)),
                ('cover_file_id', models.CharField(blank=True, help_text='files-service file UUID', max_length=64, null=True)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('applying_url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_employer', models.JSONField(blank=True, help_text='Last-seen raw employer object', null=True)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('detail_fetched_at', models.DateTimeField(blank=True, help_text='When a vacancy detail page last enriched this company', null=True)),
                ('needs_review', models.BooleanField(default=False, help_text='Set on reg-code conflicts / merge suggestions')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='fetcher.company')),
            ],
            options={
                'db_table': 'fetcher_company',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='fetcher.company'),
        ),
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('value', models.CharField(max_length=255)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='fetcher.company')),
            ],
            options={
                'db_table': 'fetcher_company_alias',
            },
        ),
        migrations.CreateModel(
            name='CompanyIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('employer_id', models.IntegerField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='fetcher.company')),
            ],
            options={
                'db_table': 'fetcher_company_identity',
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('reg_code', ''), _negated=True), ('reg_code__isnull', False)), fields=('reg_code',), name='unique_company_reg_code'),
        ),
        migrations.AlterUniqueTogether(
            name='companyalias',
            unique_together={('company', 'kind', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='companyidentity',
            unique_together={('source', 'employer_id')},
        ),
    ]
