# Generated by Django 5.2.8 on 2026-10-05 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0011_company_vacancy_company_companyalias_companyidentity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVacancyFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('include_keywords', models.JSONField(default=list)),
                ('exclude_keywords', models.JSONField(default=list)),
                ('include_industries', models.JSONField(default=list)),
                ('show_active_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vacancy_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fetcher_saved_vacancy_filter',
                'ordering': ('name',),
                'unique_together': {('user', 'name')},
            },
        ),
    ]
