# Generated by Django 5.2.8 on 2026-10-05 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0012_savedvacancyfilter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvacancyfilter',
            name='company_filter',
            field=models.CharField(default='all', max_length=16),
        ),
        migrations.CreateModel(
            name='CompanyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('like', 'Liked'), ('dislike', 'Disliked')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='fetcher.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fetcher_company_preference',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
