# Generated by Django 5.2.8 on 2026-10-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0013_savedvacancyfilter_company_filter_companypreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='detail_fetched_at',
            field=models.DateTimeField(help_text='When the public vacancy detail page was last fetched — by the nextjs scrape enrichment or by refetch_vacancies (null for API-only rows)', null=True),
        ),
    ]
