# Generated by Django 4.2.6 on 2026-01-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_vacancy_portal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='keywords',
            field=models.ManyToManyField(through='vacancies.VacancyContainsKeyword', to='vacancies.keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancycontainskeyword',
            unique_together={('vacancy', 'keyword')},
        ),
    ]
