# Generated by Django 5.2.8 on 2026-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0008_vacancy_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_portal_id',
            field=models.IntegerField(help_text='The ID of the vacancy on the job portal', null=True, unique=True),
        ),
    ]
