# Generated by Django 4.2.6 on 2026-01-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_alter_vacancy_vacancy_portal_id'),
    ]

    operations = [
    ]
